"""Initial Migration

Revision ID: a0c8f752df9b
Revises:
Create Date: 2021-10-05 11:31:29.560418

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0c8f752df9b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "directors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_directors_id"), "directors", ["id"], unique=False)
    op.create_index(op.f("ix_directors_name"), "directors", ["name"], unique=False)
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("imdb_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("imdb_rating", sa.Float(), nullable=False),
        sa.Column(
            "imdb_rating_count", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("director_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["director_id"],
            ["directors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_movies_director_id"), "movies", ["director_id"], unique=False
    )
    op.create_index(op.f("ix_movies_id"), "movies", ["id"], unique=False)
    op.create_index(op.f("ix_movies_image_url"), "movies", ["image_url"], unique=False)
    op.create_index(op.f("ix_movies_imdb_id"), "movies", ["imdb_id"], unique=False)
    op.create_index(
        op.f("ix_movies_imdb_rating"), "movies", ["imdb_rating"], unique=False
    )
    op.create_index(
        op.f("ix_movies_imdb_rating_count"),
        "movies",
        ["imdb_rating_count"],
        unique=False,
    )
    op.create_index(op.f("ix_movies_title"), "movies", ["title"], unique=False)
    op.create_index(op.f("ix_movies_year"), "movies", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movies_year"), table_name="movies")
    op.drop_index(op.f("ix_movies_title"), table_name="movies")
    op.drop_index(op.f("ix_movies_imdb_rating_count"), table_name="movies")
    op.drop_index(op.f("ix_movies_imdb_rating"), table_name="movies")
    op.drop_index(op.f("ix_movies_imdb_id"), table_name="movies")
    op.drop_index(op.f("ix_movies_image_url"), table_name="movies")
    op.drop_index(op.f("ix_movies_id"), table_name="movies")
    op.drop_index(op.f("ix_movies_director_id"), table_name="movies")
    op.drop_table("movies")
    op.drop_index(op.f("ix_directors_name"), table_name="directors")
    op.drop_index(op.f("ix_directors_id"), table_name="directors")
    op.drop_table("directors")
    # ### end Alembic commands ###
